on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Haskell versions
      run: |
        which cabal
        cabal --version
        ghc --version
        alex --version || true

    - name: Set installdir
      run: |
        DIR="~/.cabal/bin"
        mkdir -p "${DIR}"
        echo "${DIR}" >> "${GITHUB_PATH}"
        cabal user-config update --augment="extra-prog-path: ${DIR}"
        cabal user-config update --augment="installdir: ${DIR}"
      # cabal user-config update --augment="install-method: copy"
      # cabal user-config update --augment="overwrite-policy: always"

    - run: echo "$PATH"

    - name: Print config file
      run: |
        CFG=$(cabal --help | tail -1)
        echo ${CFG}
        cat ${CFG}
        echo "CFG=${CFG}" >> "${GITHUB_ENV}"

    - run: cabal update

    - run: cabal install --ignore-project alex-3.4.0.1

    - run: |
        alex --version
        which alex

    - run: cabal -v3 build

    - run: cabal exec -- alex --version
